name: My First Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-python:

    runs-on: ubuntu-latest

    steps:

      - name: Download Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run hello.py
        run: python hello.py